# Generated by Django 2.0.1 on 2018-01-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JediUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('score', models.IntegerField(default=-1)),
                ('is_finished', models.BooleanField(default=False)),
                ('name', models.TextField(default=None)),
                ('affiliation', models.TextField(default=None)),
            ],
        ),
    ]
