# Generated by Django 2.0.1 on 2018-01-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jediteacher', '0002_jediuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jediuser',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
