# Generated by Django 2.0.1 on 2018-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jediteacher', '0003_auto_20180119_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jediuser',
            name='affiliation',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jediuser',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
