# Generated by Django 2.0.1 on 2018-01-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jediteacher', '0004_auto_20180119_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='JediImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('label', models.TextField()),
                ('category', models.TextField()),
                ('filename', models.TextField()),
                ('enc_filename', models.TextField()),
            ],
        ),
    ]
