# Generated by Django 2.0.1 on 2018-01-20 18:11

from django.db import migrations
import pandas as pd
import os
from glob import glob
import scipy.io as sio
import re

def load_images(apps, schema_editor):
    JediImages = apps.get_model('jediteacher', 'JediImages')
    images = []
    for f in glob("/home/stethox/JEDI_KDD18/data/images/dom**"):
      folder_name = os.path.basename(f)
      splitted = re.sub('(?!^)([A-Z][a-z]+)', r' \1', folder_name).split()

      for img in os.listdir(f):
        images.append([splitted[0], splitted[1],img])

    for f in glob("/home/stethox/JEDI_KDD18/data/images/wild**"):
      folder_name = os.path.basename(f)
      splitted = re.sub('(?!^)([A-Z][a-z]+)', r' \1', folder_name).split()
      for img in os.listdir(f):
        images.append([splitted[0], splitted[1],img])


    df = pd.DataFrame(images, columns=['label','category','filename'])

    names = sio.loadmat('/home/stethox/JEDI_KDD18/data/images/nameMapping.mat')

    enc_images = []
    for i,j in names['nameMapping']:
      enc_images.append([i[0],j[0]])


    df2 = pd.DataFrame(enc_images, columns=['filename','enc_filename'])
    df2['filename'] = df2['filename'].astype(str)
    df2['enc_filename'] = df2['enc_filename'].astype(str)


    d = df.merge(df2,on='filename')

    for i in range(d.shape[0]):
        img = JediImages()
        img.file_id = i
        img.label = d.iloc[i][0]
        img.category = d.iloc[i][1]
        img.filename = d.iloc[i][2]
        img.enc_filename = d.iloc[i][3]
        img.save()


def unload_images(apps, schema_editor):
    JediImages = apps.get_model('jediteacher', 'JediImages')
    JediImages.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('jediteacher', '0005_jediimages'),
    ]

    operations = [
        migrations.RunPython(load_images, reverse_code=unload_images)
    ]

