# Generated by Django 2.0.1 on 2018-01-20 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jediteacher', '0006_auto_20180120_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('yl', models.IntegerField()),
                ('y', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='jediuser',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='jediuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jediuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jediuser',
            name='score',
        ),
        migrations.RemoveField(
            model_name='jediuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='jediuser',
            name='algorithm',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jediuser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
