# Generated by Django 2.0.1 on 2018-01-20 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jediteacher', '0007_auto_20180120_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlabels',
            name='algorithm',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userlabels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlabels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
