# Generated by Django 2.0.1 on 2018-01-20 17:37
from glob import glob
from django.db import migrations
import os

def load_memory_images(apps, schema_editor):
    MemoryImages = apps.get_model('memory', 'MemoryImages')
    for i,f in enumerate(glob('/home/arun/code/github/JEDI_KDD18/data/memory/*.jpg')):
        img = MemoryImages()
        img.file_id = i
        img.file_name = os.path.basename(f)
        img.save()

def unload_memory_images(apps, schema_editor):
    MemoryImages = apps.get_model('memory', 'MemoryImages')
    MemoryImages.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_memory_images, reverse_code=unload_memory_images)
    ]
